class_name Constants extends Node


enum WORD_TYPE {WEAPON, ASPECT, ELEMENT, ADJECTIVE, REACTION, EFFECT}
enum ASPECT {MIGHT, MIND, GRACE, WILL, SENSE, LUCK}
enum ELEMENT {WATER, WIND, FIRE, EARTH, ORDER, LIGHT, LIFE, CHAOS, DARK, DEATH}
